Month 12/step 1
AndreiKolosov/algososh pull request #2
Opened 2022-10-19 17:15 UTC by AndreiKolosov

2022-10-19 19:11 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;

### **Но есть несколько замечаний, которые нужно исправить:**

- По чек-листу. Функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента; Проверьте во всём проекте.

- По чек-листу. Классы, описывающие работу структур данных, вынесены в отдельные файлы в папке соответствующего компонента.

- Стек

  - исправьте поведение кнопок, они должны быть в состоянии disabled, когда поле пустое. На скриншоте показан правильный вариант: https://yadi.sk/d/lVstyqwvF7Zdvg.

- Очередь

  - В целом алгоритм работает верно, но если мы заполним всю очередь, а потом удалим и добавим 1 элемент, то у нас не будет надписи `top` и `tail`. Поэтому лучше запретить добавлять новые элементы когда вся очередь будет заполнена. Ниже записал видео, чтобы было понятно что я имею ввиду:

  - как это работает у вас: https://disk.yandex.ru/d/GHw6A4_oY4AOTg;
  - как это должно работать правильно: https://disk.yandex.ru/i/4p-B66yaQjeHeg;

- Связный список

  Как это должно работать правильно: https://disk.yandex.ru/i/cv6sV6I-f48CYg.

  - При удалении элемента по индексу сначала необходимо выделять цветом элементы, пока не достигнем нужного индекса. Затем очистить значение в элементе и снизу отобразить маленький кружок с удаляемым значением. А у вас постоянно при итерации, у элементов отображается кружок снизу. Ниже видео как это примерно должно выглядеть, в вашем случае достаточно просто убрать нижний кружок у лишних элементов.

  - При добавлении в tail элемент должен появиться в хвосте над элементом с надписью tail. Затем он занимает последнее место в списке и на долю секунды выделяется зелёным цветом. Теперь под новым элементом написано tail. У вас не выделяется элемент зеленым цветом.

  - По заданию, сказано: обратите внимание, что при добавлении новый элемент следует отображать над элементами списка, а при удалении — под ними. У вас же, при добавлении/удалении элементы могут быть сверху и снизу, что не является корректным.

### **Сделает код лучше:**

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить".**

2022-10-19 19:11 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  }
**Надо исправить:** По чек-листу, нужно реализовать функцию getFibonacciNumbers, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи; Вам надо исправить название а также эта функция должна возвращать результат. Также эту функцию нужно вынести в utils.ts.

2022-10-19 19:11 UTC, ArslanMustafin commented on src/utils/linked-list.ts
> +export class ListNode<T> {
**Можно лучше:** Лучше переименовать в LinkedListNode. Требование чек-листа.

2022-10-19 19:11 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +      for (let j = i + 1; j < length; j += 1) {
**Можно лучше:** Здесь и далее. Стоит создать функции сортировки таким образом, чтобы они возвращали набор шагов и далее при отображении алгоритма добавлять паузы между шагами, а не генерировать паузы непосредственно в алгоритме.

2022-10-19 19:11 UTC, ArslanMustafin commented on src/utils/queue.ts
> +    this.container[this.tail % this.size] = item;
~~**Надо исправить:** Здесь вроде можно использовать просто this.tail, честно говоря не очень понимаю вашу реализацию.~~

2022-10-19 19:11 UTC, ArslanMustafin commented on src/utils/queue.ts
> +    this.container[this.head % this.size] = null;
~~**Надо исправить:** Аналогичная проблема, которая была в методе enqueue.~~

2022-10-19 19:11 UTC, ArslanMustafin commented on src/utils/queue.ts
> +    return this.container[this.head % this.size];
~~**Надо исправить:** Аналогичная проблема, которая была в методе enqueue.~~

2022-10-20 07:26 UTC, AndreiKolosov commented on src/utils/queue.ts
> +    this.container[this.tail % this.size] = item;
Эта реализация взята из тренажера. Указывая индекс таким образом, я могу реализовать "закольцованную" очередь.

2022-10-20 07:26 UTC, AndreiKolosov commented on src/utils/queue.ts
> +    this.container[this.head % this.size] = null;
Эта реализация взята из тренажера. Указывая индекс таким образом, я могу реализовать "закольцованную" очередь.

2022-10-20 07:26 UTC, AndreiKolosov commented on src/utils/queue.ts
> +    return this.container[this.head % this.size];
Эта реализация взята из тренажера. Указывая индекс таким образом, я могу реализовать "закольцованную" очередь.

2022-10-20 09:23 UTC, AndreiKolosov commented
По поводу индекса в классе Queue - Эта реализация взята из тренажера. Указывая индекс таким образом, я могу реализовать "закольцованную" очередь.

2022-10-20 16:33 UTC, ArslanDev666 commented
> По поводу индекса в классе Queue - Эта реализация взята из тренажера. Указывая индекс таким образом, я могу реализовать "закольцованную" очередь. Баги пофиксил.

Супер, понял. Тогда замечание отменяется.

2022-10-20 17:26 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента. Проверьте во всех алгоритмах;

  Я имею ввиду getFibonacciNumbers, и похожие функции, которые не взаимодействуют с компонентом. Их нужно вынести в отдельный файл utils.ts, в папке соответствующего компонента. Например `getFibonacciNumbers` следует вынести в файл - `fibonacci-page/utils.ts`;

- Связный список

  - По заданию, сказано: обратите внимание, что при добавлении новый элемент следует отображать над элементами списка, а при удалении — под ними. У вас же, при добавлении/удалении элементы могут быть сверху и снизу, что не является корректным.

    Показал баг на видео. https://disk.yandex.ru/i/_0uxAaa3Qc-2bw

2022-10-20 19:35 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Теперь всё круто работает 👍🏻.

### **Вы молодец! Была проделана большая работа по рефакторингу кода. Работа принята.🔥**

2022-10-20 21:04 UTC, merged