Month 13/step 1
AndreiKolosov/algososh pull request #3
Opened 2022-11-04 12:24 UTC by AndreiKolosov

2022-11-04 14:12 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Работа проделана огромная.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- все юнит-тесты проходят успешно;
- все Snapshots-тесты проходят успешны;
- все cypress-тесты проходят успешно;

### **Но есть несколько замечаний, которые нужно исправить:**

- Покрытие говорит, что у вас не протестировано поведение компонента components/ui/button при разных значениях пропса sorting, а также linkedList. Чтобы проверить покрытие тестами всех компонентов используйте команду react-scripts test --coverage --watchAll.

  https://yadi.sk/d/ud47GCk6epxp5g

- https://yadi.sk/d/ud47GCk6epxp5g - Нужно настроить базовый url для cypress.

### **Сделает код лучше:**

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-04 14:12 UTC, ArslanDev666 commented on cypress/e2e/app-routing.spec.cy.js
> +  });
**Надо исправить:** Здесь и далее вам лучше проверять title на разные текста, а не только на `МБОУ АЛГОСОШ`.

2022-11-04 14:12 UTC, ArslanDev666 commented on cypress/e2e/fibonacci-page.cy.js
> +    cy.visit('/fibonacci');
**Надо исправить:** Проверьте везде, путь должен содержать localhost, иначе могут быть ошибки.

```
http://localhost:3000/fibonacci
```

2022-11-04 14:12 UTC, ArslanDev666 commented on cypress/e2e/queue-page.cy.js
> +    cy.get('button').eq(3).should('be.disabled');
**Можно лучше:** Здесь и в похожих местах. Попробуйте использовать перебор .each https://docs.cypress.io/api/commands/each

2022-11-04 14:33 UTC, AndreiKolosov commented on cypress/e2e/app-routing.spec.cy.js
> +  });
Проверяя заголовок на наличие текста 'МБОУ АЛГОСОШ' я удостоверяюсь, что попал обратно на главную страницу. Проверку строил исходя из логики: 

1. Зашел на главную
2. Проверил заголовок, убедился что это главная страница
3. Нашел нужную ссылку
4. Перешел на страницу

Согласен, забыл добавить проверку заголовка на целевой странице, это исправил.

2022-11-04 14:35 UTC, AndreiKolosov commented on cypress/e2e/fibonacci-page.cy.js
> +    cy.visit('/fibonacci');
В cypress.config.js прописан baseUrl  "http://localhost:3000/algososh" чтобы в каждом тесте не писать путь целиком, а использовать относительный

2022-11-05 09:23 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

2022-11-05 14:52 UTC, merged